repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black


