set(MLIR_TENSORRT_VERSION_MAJOR "0")
set(MLIR_TENSORRT_VERSION_MINOR "4")
set(MLIR_TENSORRT_VERSION_PATCH "6")
set(MLIR_TENSORRT_VERSION
  "${MLIR_TENSORRT_VERSION_MAJOR}.${MLIR_TENSORRT_VERSION_MINOR}.${MLIR_TENSORRT_VERSION_PATCH}")

# The source release script replaces the empty string with a actual
# hash, so don't change the default here.
set(MLIR_TENSORRT_GIT_HASH "")

set(CPACK_PACKAGE_VERSION_MAJOR ${MLIR_TENSORRT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${MLIR_TENSORRT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${MLIR_TENSORRT_VERSION_PATCH})
