# version.bzl

MLIR_TENSORRT_VERSION_MAJOR = "0"
MLIR_TENSORRT_VERSION_MINOR = "1"
MLIR_TENSORRT_VERSION_PATCH = "34"
MLIR_TENSORRT_VERSION = "{}.{}.{}".format(MLIR_TENSORRT_VERSION_MAJOR, MLIR_TENSORRT_VERSION_MINOR, MLIR_TENSORRT_VERSION_PATCH)
