set(MLIR_TENSORRT_VERSION_MAJOR "0")
set(MLIR_TENSORRT_VERSION_MINOR "4")
set(MLIR_TENSORRT_VERSION_PATCH "3")
set(MLIR_TENSORRT_VERSION
  "${MLIR_TENSORRT_VERSION_MAJOR}.${MLIR_TENSORRT_VERSION_MINOR}.${MLIR_TENSORRT_VERSION_PATCH}")
