set(MLIR_TENSORRT_VERSION_MAJOR "0")
set(MLIR_TENSORRT_VERSION_MINOR "1")
set(MLIR_TENSORRT_VERSION_PATCH "33")
set(MLIR_TENSORRT_VERSION
  "${MLIR_TENSORRT_VERSION_MAJOR}.${MLIR_TENSORRT_VERSION_MINOR}.${MLIR_TENSORRT_VERSION_PATCH}")

