repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

repos:
-   repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
    - id: black

repos:
  - repo: local
    hooks:
      - id: add-license
        name: Add License
        entry: python tripy/tools/add_copyright.py
        language: python
        stages: [pre-commit]
        files: \.py$
