FROM python:3.11

LABEL org.opencontainers.image.description="Tripy Release Container"

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir --upgrade nvtripy \
        -f https://nvidia.github.io/TensorRT-Incubator/packages.html
