# GenerateEmbeddedFileGroup.cmake
#
# CMake script that generates a C++ source file embedding a list of text files
# as raw string literals. This allows embedding arbitrary file groups into the
# compiler binary so that support files can be emitted without reading the
# source tree at runtime.
#
# Expected variables:
# - OUTPUT: output .cpp file path
# - INPUT_FILES: CMake list of absolute input file paths
# - REL_PATHS: CMake list of relative/basename paths (same length as INPUT_FILES)
# - GROUP_NAME: name of the file group (e.g. "StandaloneCPP"); used to derive
#               function names getEmbedded<GroupName>Files() and
#               getEmbedded<GroupName>FileContents()
# - HEADER_INCLUDE: the include path for the corresponding header file
# - NAMESPACE: C++ namespace for the generated functions

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: OUTPUT is required")
endif()
if(NOT DEFINED INPUT_FILES)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: INPUT_FILES is required")
endif()
if(NOT DEFINED REL_PATHS)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: REL_PATHS is required")
endif()
if(NOT DEFINED GROUP_NAME)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: GROUP_NAME is required")
endif()
if(NOT DEFINED HEADER_INCLUDE)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: HEADER_INCLUDE is required")
endif()
if(NOT DEFINED NAMESPACE)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: NAMESPACE is required")
endif()

list(LENGTH INPUT_FILES _n_inputs)
list(LENGTH REL_PATHS _n_rels)
if(NOT _n_inputs EQUAL _n_rels)
  message(FATAL_ERROR "GenerateEmbeddedFileGroup: INPUT_FILES and REL_PATHS must have same length")
endif()

# Derive the header guard and file-level banner from the output basename.
cmake_path(GET OUTPUT STEM _output_stem)

file(WRITE "${OUTPUT}" "//===- ${_output_stem}.cpp ---*- C++ -*-===//\n")
file(APPEND "${OUTPUT}" "//\n")
file(APPEND "${OUTPUT}" "// This file is generated by compiler/cmake/GenerateEmbeddedFileGroup.cmake.\n")
file(APPEND "${OUTPUT}" "// Do not edit manually.\n")
file(APPEND "${OUTPUT}" "//\n")
file(APPEND "${OUTPUT}" "#include \"${HEADER_INCLUDE}\"\n")
file(APPEND "${OUTPUT}" "#include \"llvm/ADT/StringMap.h\"\n")
file(APPEND "${OUTPUT}" "\n")
file(APPEND "${OUTPUT}" "namespace ${NAMESPACE} {\n\n")

set(_var_names "")
math(EXPR _last "${_n_inputs} - 1")
foreach(i RANGE 0 ${_last})
  list(GET INPUT_FILES ${i} _in)
  list(GET REL_PATHS ${i} _rel)

  # Sanitize a C++ identifier for the backing char array name.
  set(_var "${_rel}")
  string(REPLACE "/" "_" _var "${_var}")
  string(REPLACE "." "_" _var "${_var}")
  string(REPLACE "-" "_" _var "${_var}")

  file(READ "${_in}" _contents)

  file(APPEND "${OUTPUT}" "static constexpr char k_${_var}[] = R\"__MTRT_EMBED__(\n")
  file(APPEND "${OUTPUT}" "${_contents}")
  file(APPEND "${OUTPUT}" "\n)__MTRT_EMBED__\";\n\n")

  list(APPEND _var_names "${_var}")
endforeach()

file(APPEND "${OUTPUT}" "static const EmbeddedTextFile kFiles[] = {\n")
foreach(i RANGE 0 ${_last})
  list(GET REL_PATHS ${i} _rel)
  list(GET _var_names ${i} _var)
  file(APPEND "${OUTPUT}" "  {\"${_rel}\", llvm::StringRef(k_${_var}, sizeof(k_${_var}) - 1)},\n")
endforeach()
file(APPEND "${OUTPUT}" "};\n\n")

file(APPEND "${OUTPUT}" "llvm::ArrayRef<EmbeddedTextFile> getEmbedded${GROUP_NAME}Files() {\n")
file(APPEND "${OUTPUT}" "  return llvm::ArrayRef<EmbeddedTextFile>(kFiles);\n")
file(APPEND "${OUTPUT}" "}\n\n")

file(APPEND "${OUTPUT}" "llvm::StringRef getEmbedded${GROUP_NAME}FileContents(llvm::StringRef path) {\n")
file(APPEND "${OUTPUT}" "  for (const auto &f : kFiles) {\n")
file(APPEND "${OUTPUT}" "    if (f.path == path)\n")
file(APPEND "${OUTPUT}" "      return f.contents;\n")
file(APPEND "${OUTPUT}" "  }\n")
file(APPEND "${OUTPUT}" "  return {};\n")
file(APPEND "${OUTPUT}" "}\n\n")

file(APPEND "${OUTPUT}" "} // namespace ${NAMESPACE}\n")
