#include <cuda.h>
#include <cuda_runtime_api.h>

#include <cstdint>
#include <cstdio>

#include "MTRTRuntimeStatus.h"

extern CUstream cuda_launch_argpack_test_cuda_stream;

// Aggregated init/destroy helpers generated by the EmitC host backend.
int32_t cuda_launch_argpack_test_initialize_all();
void cuda_launch_argpack_test_destroy_all();

int32_t run();

int main() {
  // The generated code reads the stream from a global.
  cuda_launch_argpack_test_cuda_stream = nullptr;

  int32_t initRc = cuda_launch_argpack_test_initialize_all();
  if (initRc != 0) {
    // Best-effort: runtime stores a thread-local message for the last error.
    std::fprintf(stderr, "%s\n", mtrt::get_last_error_message());
    return initRc;
  }

  int32_t rc = run();

  cuda_launch_argpack_test_destroy_all();
  return rc;
}
