from tripy import utils
from tripy.backend.mlir.mlir import mlir_wrapper, void_ptr
from tripy.common.logging import logger


class Compiler:
    def __init__(self) -> None:
        self.compiler = mlir_wrapper()

    @staticmethod
    def remove_stablehlo_constants(mlir_textual) -> str:
        lines = mlir_textual.split("\n")

        def replace_dense_data(text):
            const_start_index = text.find("<") + 1
            const_end_index = text.find(">") - 1
            start_index = text.find(": tensor<") + 9

            substr = text[start_index:]
            dims = substr.split("x")
            dims = [int(dim) for dim in dims if dim.isdigit()]

            if utils.should_omit_constant_in_str(dims):
                return text[:const_start_index] + "..." + text[const_end_index + 1 :]
            return text

        replaced = [replace_dense_data(line) if "stablehlo.constant dense" in line else line for line in lines]
        return "\n".join(replaced)

    def compile_stabehlo_program(self, stablehlo_program: str) -> void_ptr:
        return self.compiler.compile(stablehlo_program)

    @utils.log_time
    def compile(self, mlir) -> void_ptr:
        """
        Compiles an MLIR module into an MLIR-TRT executable

        Args:
            mlir: The MLIR module.

        Returns:
            Pointer to the executable generated by the mlir-tensorrt compiler.
        """
        mlir_textual = str(mlir)
        logger.stablehlo(
            lambda: f"{utils.prefix_with_line_numbers(Compiler.remove_stablehlo_constants(mlir_textual))}\n"
        )
        return self.compile_stabehlo_program(mlir_textual)
