# GenerateEmbeddedStandaloneCPP.cmake
#
# CMake script that generates a C++ source file embedding a list of text files
# as raw string literals. Intended to embed the StandaloneCPP runtime sources
# into the compiler so that support files can be emitted without reading the
# source tree at runtime.
#
# Expected variables:
# - OUTPUT: output .cpp file path
# - INPUT_FILES: CMake list of absolute input file paths
# - REL_PATHS: CMake list of relative/basename paths (same length as INPUT_FILES)

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "GenerateEmbeddedStandaloneCPP: OUTPUT is required")
endif()
if(NOT DEFINED INPUT_FILES)
  message(FATAL_ERROR "GenerateEmbeddedStandaloneCPP: INPUT_FILES is required")
endif()
if(NOT DEFINED REL_PATHS)
  message(FATAL_ERROR "GenerateEmbeddedStandaloneCPP: REL_PATHS is required")
endif()

list(LENGTH INPUT_FILES _n_inputs)
list(LENGTH REL_PATHS _n_rels)
if(NOT _n_inputs EQUAL _n_rels)
  message(FATAL_ERROR "GenerateEmbeddedStandaloneCPP: INPUT_FILES and REL_PATHS must have same length")
endif()

file(WRITE "${OUTPUT}" "//===- EmbeddedStandaloneCPP.cpp ------------------------------*- C++ -*-===//\n")
file(APPEND "${OUTPUT}" "//\n")
file(APPEND "${OUTPUT}" "// This file is generated by compiler/cmake/GenerateEmbeddedStandaloneCPP.cmake.\n")
file(APPEND "${OUTPUT}" "// Do not edit manually.\n")
file(APPEND "${OUTPUT}" "//\n")
file(APPEND "${OUTPUT}" "#include \"mlir-tensorrt/Conversion/HostToEmitC/EmbeddedStandaloneCPP.h\"\n")
file(APPEND "${OUTPUT}" "#include \"llvm/ADT/StringMap.h\"\n")
file(APPEND "${OUTPUT}" "\n")
file(APPEND "${OUTPUT}" "namespace mtrt::compiler::emitc_support {\n\n")

set(_var_names "")
math(EXPR _last "${_n_inputs} - 1")
foreach(i RANGE 0 ${_last})
  list(GET INPUT_FILES ${i} _in)
  list(GET REL_PATHS ${i} _rel)

  # Sanitize a C++ identifier for the backing char array name.
  set(_var "${_rel}")
  string(REPLACE "/" "_" _var "${_var}")
  string(REPLACE "." "_" _var "${_var}")
  string(REPLACE "-" "_" _var "${_var}")

  file(READ "${_in}" _contents)

  file(APPEND "${OUTPUT}" "static constexpr char k_${_var}[] = R\"__MTRT_EMBED__(\n")
  file(APPEND "${OUTPUT}" "${_contents}")
  file(APPEND "${OUTPUT}" "\n)__MTRT_EMBED__\";\n\n")

  list(APPEND _var_names "${_var}")
endforeach()

file(APPEND "${OUTPUT}" "static const EmbeddedTextFile kFiles[] = {\n")
foreach(i RANGE 0 ${_last})
  list(GET REL_PATHS ${i} _rel)
  list(GET _var_names ${i} _var)
  file(APPEND "${OUTPUT}" "  {\"${_rel}\", llvm::StringRef(k_${_var}, sizeof(k_${_var}) - 1)},\n")
endforeach()
file(APPEND "${OUTPUT}" "};\n\n")

file(APPEND "${OUTPUT}" "llvm::ArrayRef<EmbeddedTextFile> getEmbeddedStandaloneCPPFiles() {\n")
file(APPEND "${OUTPUT}" "  return llvm::ArrayRef<EmbeddedTextFile>(kFiles);\n")
file(APPEND "${OUTPUT}" "}\n\n")

file(APPEND "${OUTPUT}" "llvm::StringRef getEmbeddedStandaloneCPPFileContents(llvm::StringRef path) {\n")
file(APPEND "${OUTPUT}" "  for (const auto &f : kFiles) {\n")
file(APPEND "${OUTPUT}" "    if (f.path == path)\n")
file(APPEND "${OUTPUT}" "      return f.contents;\n")
file(APPEND "${OUTPUT}" "  }\n")
file(APPEND "${OUTPUT}" "  return {};\n")
file(APPEND "${OUTPUT}" "}\n\n")

file(APPEND "${OUTPUT}" "} // namespace mtrt::compiler::emitc_support\n")
