# Perform L1 test, build docs
name: Tripy L1

on:
  # Runs at 2am pst (9am utc) every day
  schedule:
    - cron: "0 9 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  l1-test:
    runs-on: tripy-self-hosted
    container:
      image: ghcr.io/nvidia/tensorrt-incubator/tripy:latest
      volumes:
        - ${{ github.workspace }}/tripy:/tripy
      options: --gpus all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v5
    - name: build-docs
      run: |
        cd /tripy/
        python3 docs/generate_rsts.py
        sphinx-build build/doc_sources build/docs -c docs/ -j 6 -W
    - name: l1-test
      run: |
        cd /tripy/
        pytest tests/ -v --durations=-1
